Models/CookieConsentSettingsPart.cs
using Orchard.ContentManagement;
using Orchard.ContentManagement.FieldStorage.InfosetStorage;

namespace Datwendo.CookieConsent.Models {

    public class CookieConsentSettingsPart : ContentPart {
        public string CookieName {
            get {
                var nm = this.As<InfosetPart>().Get<CookieConsentSettingsPart>("CookieName");
                return nm ?? "Consent";
            }
            set {
                this.As<InfosetPart>().Set<CookieConsentSettingsPart>("CookieName", value);
            }
        }

        public int CookieExpireDelay {
            get {
                string days = this.As<InfosetPart>().Get<CookieConsentSettingsPart>("CookieExpireDelay");
                int nb = 0;
                if (int.TryParse(days, out nb))
                    return nb;
                return 30;
            }
            set {
                this.As<InfosetPart>().Set<CookieConsentSettingsPart>("CookieExpireDelay", value.ToString());
            }
        }

        public string ButtonText {
            get {
                var nm = this.As<InfosetPart>().Get<CookieConsentSettingsPart>("ButtonText");
                return nm ?? "Accept";
            }
            set {
                this.As<InfosetPart>().Set<CookieConsentSettingsPart>("ButtonText", value);
            }
        }

        public string HeaderText {
            get {
                return this.As<InfosetPart>().Get<CookieConsentSettingsPart>("HeaderText");
            }
            set {
                this.As<InfosetPart>().Set<CookieConsentSettingsPart>("HeaderText", value);
            }
        }

        public string Text {
            get {
                return this.As<InfosetPart>().Get<CookieConsentSettingsPart>("Text");
            }
            set {
                this.As<InfosetPart>().Set<CookieConsentSettingsPart>("Text", value);
            }
        }
    }
}

Controllers/CookieConsentController.cs
using System;
using System.Web.Mvc;

namespace Datwendo.CookieConsent.Controllers {

    public class CookieConsentController : Controller {
        public CookieConsentController() {
        }

        [HttpPost]
        public JsonResult Accept(string referrer) {
            return new JsonResult { Data = string.Format("Ok-{0:u}",DateTime.Now) };
        }
    }
}

Views/CookieConsent.cshtml
@model dynamic
@{
        Script.Require("jscookie");
}
@if (!String.IsNullOrEmpty(Model.Text)) {
    <div id="cookieconsent" class="cookieconsent">
    @if (Model.HeaderText != null) {
        <div class="header">@Model.HeaderText</div>
    }
    @if (Model.HtmlText != null) {
        <div class="body">@Model.HtmlText</div>
    }
        <button type="button" class="button button-accept" data-url="@Url.Action("Accept","CookieConsent", new { Area = "Datwendo.CookieConsent", ReturnUrl = Request.Url})">@Model.ButtonText</button>
    </div>
}

@using (Script.Foot()) {
    <script type="text/javascript">
        $(function () {
            // Assign the js-cookie api to a different variable and restore the original "window.Cookies"
            var Cookies2 = Cookies.noConflict();
            var antiForgeryToken = '@HttpUtility.JavaScriptStringEncode(Html.AntiForgeryTokenValueOrchard().ToString())';
            var cookieName = '@Model.CookieName';
            var cookieLife= @Model.Delay;
            $('.button-accept').click(function () {
                var postUrl = $(this).data('url');
                $.ajax({
                    type: 'POST',
                    url: postUrl,
                    async: false,
                    data: {
                        __RequestVerificationToken: antiForgeryToken,
                        referrer: document.referrer
                    },
                    success: function (data) {
                        Cookies2.set(cookieName,data , { expires: cookieLife });
                        $('#cookieconsent').hide();
                    },
                    fail: function (result) {
                        alert("An error occured: " + result);
                    }
                });
            });
        });
    </script>
}

Views/EditorTemplates/Parts/CookieConsentSettings.cshtml
@using Datwendo.CookieConsent.Models
@using Orchard.ContentManagement
@using Orchard.Environment.Descriptor.Models
@using Orchard.Localization
@using System.Globalization


@model CookieConsentSettingsPart

@{
    var shellDescriptor = WorkContext.Resolve<ShellDescriptor>();
    var currentCulture = CultureInfo.GetCultureInfo(WorkContext.CurrentCulture);
}


<script type="text/javascript">
    var mediaPickerEnabled = @(shellDescriptor.Features.Any(x => x.Name == "Orchard.MediaPicker") ? "true" : "false");
    var mediaLibraryEnabled = @(shellDescriptor.Features.Any(x => x.Name == "Orchard.MediaLibrary") ? "true" : "false");
    var directionality = '@WorkContext.GetTextDirection((IContent)Model.ContentItem)';
    var language =  '@currentCulture.Name.Replace('-', '_')';
    var autofocus = true;
</script>

@{
    Script.Require("OrchardTinyMce");
    Script.Require("jQueryColorBox");
    Style.Require("jQueryColorBox");
}
<h1>@T("Cookie consent parameters")</h1>
<fieldset>
    @Html.LabelFor(m => m.CookieName, T("Cookie name"))
    @Html.TextBoxFor(m => m.CookieName, new { @class = "text medium" })
    <span class="hint">@T("Enter the name of the consent cookie")</span>
</fieldset>
<fieldset>
    @Html.LabelFor(m => m.CookieExpireDelay, T("Cookie expiration delay"))
    @Html.TextBoxFor(m => m.CookieExpireDelay, new { @class = "text medium" })
    @Html.ValidationMessage("CookieExpireDelay", "*")
    <span class="hint">@T("Enter the value in days for the cookie expiration delay")</span>
</fieldset>
<fieldset>
    @Html.LabelFor(m => m.HeaderText, T("Header Text"))
    @Html.TextBoxFor(m => m.HeaderText, new { @class = "text medium" })
    <span class="hint">@T("Enter the text of the header")</span>
</fieldset>
<fieldset>
    @Html.LabelFor(m => m.ButtonText, T("Button Text"))
    @Html.TextBoxFor(m => m.ButtonText, new { @class = "text medium" })
    <span class="hint">@T("Enter the text of the accept button")</span>
</fieldset>
<fieldset>
    <label for="Text">@T("Content of the consent area")</label>
    @Html.TextArea("Text", (string)Model.Text, 25, 80,
     new Dictionary<string, object> {
        {"class", "html tinymce"},
        {"data-mediapicker-uploadpath",""},
        {"data-mediapicker-title",T("Insert/Update Media")},
        {"style", "width:100%"}
     })
</fieldset>